snapshot:
  only:
    refs:
      - master
  script:
    - git checkout snapshot
    - git reset --hard originmaster
    - git reset --soft origin/snapshot
    - dune build redirect.opam
    - git add --force redirect.opam
    - if
        git commit
          --message="Snapshot for commit $(git rev-parse origin/master)";
      then
        git remote set-url origin $(git remote get-url origin
          | sed 's#^https://\([^/@]*@\)\?\([^/@]*\)/#git@\2:#');
        git push;
      fi
